In [2]:
import pandas as pd

In [3]:
# 1. Data Exploration and Cleaning
# Load the dataset into a Pandas DataFrame and display the first 5 rows.

data = pd.read_csv("online_retail_sales_Large.csv")
data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23

In [4]:
# Check the dataset shape, column names, data types, and summary statistics.

print("Dataset shape: \n",data.shape)
print("column names: \n",data.columns.to_list())
print("Data Types: \n",data.dtypes)
print("summary statistics :\n",data.describe())

Dataset shape:
 (50000, 11)
column names:
 ['Order_ID', 'Customer_ID', 'Order_Date', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Payment_Method', 'Order_Status', 'City', 'Total_Amount']
Data Types:
 Order_ID            int64
Customer_ID         int64
Order_Date         object
Product            object
Category           object
Quantity            int64
Unit_Price        float64
Payment_Method     object
Order_Status       object
City               object
Total_Amount      float64
dtype: object
summary statistics :
            Order_ID   Customer_ID      Quantity    Unit_Price  Total_Amount
count  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000
mean   25000.500000   5494.083720     12.493440   1259.940694  15776.022701
std    14433.901067   2601.545347      6.901944    715.936278  13461.642349
min        1.000000   1000.000000      1.000000     20.010000     22.340000
25%    12500.750000   3232.750000      6.000000    639.095000   4619.632500
50%    25000.500000   5497.000000     13.000000   1261.480000  11949.390000
75%    37500.250000   7746.000000     18.000000   1876.660000  23997.630000
max    50000.000000   9999.000000     24.000000   2499.960000  59958.960000

In [5]:
# Identify missing values in each column.
print(data.isnull().sum())

Order_ID          0
Customer_ID       0
Order_Date        0
Product           0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
Order_Status      0
City              0
Total_Amount      0
dtype: int64

In [6]:
# Handle missing values appropriately:
# Numerical columns: fill with mean or median.
# Categorical columns: fill with mode or drop.

data['Product'] = data['Product'].fillna('Unkown')
data['Unit_Price'] = data['Unit_Price'].fillna(data['Unit_Price'].median())

In [7]:
# Convert Order_Date into datetime format.
data['Order_Date'] = pd.to_datetime(data['Order_Date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        50000 non-null  int64
 1   Customer_ID     50000 non-null  int64
 2   Order_Date      50000 non-null  datetime64[ns]
 3   Product         50000 non-null  object
 4   Category        50000 non-null  object
 5   Quantity        50000 non-null  int64
 6   Unit_Price      50000 non-null  float64
 7   Payment_Method  50000 non-null  object
 8   Order_Status    50000 non-null  object
 9   City            50000 non-null  object
 10  Total_Amount    50000 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 4.2+ MB

In [8]:
# Extract Year, Month, and Day from Order_Date into new columns.
data['Day'] = data['Order_Date'].dt.day
data['Month'] = data['Order_Date'].dt.month
data['Year'] = data['Order_Date'].dt.year
data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,2023
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023

In [9]:
# 2. Data Selection and Filtering
# Retrieve all orders placed in March 2024.
all_order_march_2024 = data[(data['Month']==3) & (data['Year']==2024)]
all_order_march_2024.head(8)

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
32,33,2267,2024-03-04,Laptop,Clothing,6,1892.98,UPI,Completed,Hyderabad,11357.88,4,3,2024
34,35,4556,2024-03-20,TV,Accessories,13,691.15,Cash,Returned,Bangalore,8984.95,20,3,2024
36,37,9838,2024-03-29,TV,Home Appliances,9,1138.31,UPI,Completed,Chennai,10244.79,29,3,2024
64,65,7439,2024-03-20,Shoes,Accessories,10,2078.13,PayPal,Completed,Hyderabad,20781.30,20,3,2024
82,83,3027,2024-03-29,Mobile,Accessories,18,56.06,Cash,Completed,Hyderabad,1009.08,29,3,2024
95,96,8215,2024-03-25,Laptop,Electronics,16,113.54,Debit Card,Completed,Bangalore,1816.64,25,3,2024
125,126,7892,2024-03-11,TV,Accessories,12,1777.17,Cash,Completed,Pune,21326.04,11,3,2024
135,136,6450,2024-03-02,Camera,Home Appliances,15,1222.36,PayPal,Completed,Kolkata,18335.40,2,3,2024

In [10]:
# Find all orders where:
# Total_Amount > 10000
# Category is Electronics.
category_electronic_totalAmount_10000 =  data[(data['Category']=='Electronics') & (data['Total_Amount'] > 10000)]
category_electronic_totalAmount_10000.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
18,19,5555,2023-08-22,Mobile,Electronics,10,2478.51,PayPal,Completed,Bangalore,24785.10,22,8,2023
23,24,8849,2023-08-17,TV,Electronics,19,967.10,PayPal,Cancelled,Bangalore,18374.90,17,8,2023
30,31,2899,2024-07-29,Camera,Electronics,22,2015.96,UPI,Cancelled,Pune,44351.12,29,7,2024
40,41,8513,2024-12-15,Camera,Electronics,19,2336.76,Debit Card,Cancelled,Delhi,44398.44,15,12,2024
56,57,7873,2024-02-20,Headphones,Electronics,23,1348.05,Debit Card,Completed,Delhi,31005.15,20,2,2024

In [11]:
# Select only Completed orders.
completed_order = data[data['Order_Status']=='Completed']
completed_order.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,2023
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023

In [12]:
# Retrieve orders placed from Mumbai or Delhi.
orders_placed_Mumbai_Delhi = data[(data['City']=='Pune') | (data['City']=='Mumbai')]
orders_placed_Mumbai_Delhi.head(10)

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023
10,11,2685,2023-08-25,Watch,Clothing,8,1525.58,UPI,Completed,Pune,12204.64,25,8,2023
14,15,6311,2023-09-13,Camera,Clothing,12,153.94,Debit Card,Returned,Mumbai,1847.28,13,9,2023
20,21,7396,2024-05-07,Shoes,Home Appliances,2,2212.34,PayPal,Cancelled,Mumbai,4424.68,7,5,2024
30,31,2899,2024-07-29,Camera,Electronics,22,2015.96,UPI,Cancelled,Pune,44351.12,29,7,2024
31,32,8734,2023-09-02,Tablet,Home Appliances,13,123.00,UPI,Completed,Pune,1599.00,2,9,2023
35,36,4890,2023-08-21,TV,Clothing,16,1180.10,Credit Card,Completed,Mumbai,18881.60,21,8,2023
37,38,6393,2023-12-15,Tablet,Home Appliances,11,2439.66,Credit Card,Completed,Pune,26836.26,15,12,2023

In [13]:
# 3. Data Manipulation and Feature Engineering
# Create a new column Discounted_Amount:
    # Apply a 10 percent discount on orders where Total_Amount > 8000.
data['Discounted_Amount'] = data['Total_Amount'].apply(lambda x : x * 0.90 if x > 8000 else x)
data.head(5)

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year,Discounted_Amount
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023,6408.050
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,2023,11772.000
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023,5266.020
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024,18121.320
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023,8567.307

In [14]:
# Create a column Price_Level based on Total_Amount:
    # Low: Below 2000
    # Medium: 2000 to 8000
    # High: Above 8000
price_lables = ['Low','Medium','High']
data['Price_Level'] = pd.cut(data['Total_Amount'],bins=[-float('inf'),2000,8000,float('inf')],labels=price_lables)
data.head(5)

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year,Discounted_Amount,Price_Level
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023,6408.050,Medium
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,2023,11772.000,High
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023,5266.020,Medium
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024,18121.320,High
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023,8567.307,High

In [51]:
# Create a new column Revenue_Per_Item:
    # Revenue_Per_Item = Total_Amount / Quantity
data['Revenue_Per_Item'] = data['Total_Amount'] / data['Quantity']
data.head(10)

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year,Discounted_Amount,Price_Level,Revenue_Per_Item
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023,6408.050,Medium,582.55
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,2023,11772.000,High,1635.00
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023,5266.020,Medium,877.67
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024,18121.320,High,2237.20
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023,8567.307,High,1359.89
5,6,7265,2024-01-14,Camera,Accessories,6,1305.34,UPI,Completed,Bangalore,7832.04,14,1,2024,7832.040,Medium,1305.34
6,7,1466,2024-05-06,Tablet,Clothing,6,2312.03,Cash,Completed,Delhi,13872.18,6,5,2024,12484.962,High,2312.03
7,8,5426,2024-11-14,Laptop,Accessories,20,2197.05,Credit Card,Completed,Kolkata,43941.00,14,11,2024,39546.900,High,2197.05
8,9,6578,2023-10-31,Headphones,Electronics,15,90.82,Credit Card,Completed,Delhi,1362.30,31,10,2023,1362.300,Low,90.82
9,10,9322,2024-05-12,Tablet,Accessories,24,1529.67,Cash,Cancelled,Chennai,36712.08,12,5,2024,33040.872,High,1529.67

In [16]:
# Drop the Product column if more than 40 percent of values are missing.

missing_values = data['Product'].isnull().mean()
# print(missing_values)
if missing_values > 40:
    data.drop(data['Product'],inplace=True)
    print("Drop Product Table")
else:
    print("No missing values")

No missing values

In [17]:
# 4. Aggregation and Business Insights
    # Find the total revenue per Category.
total_revenue_per_Category = data.groupby('Category')['Total_Amount'].sum().reset_index()
total_revenue_per_Category

          Category  Total_Amount
0      Accessories  1.994063e+08
1         Clothing  1.982393e+08
2      Electronics  1.951642e+08
3  Home Appliances  1.959914e+08

In [18]:
#Calculate the average order value per Payment_Method.
avg_order_value = data.groupby('Payment_Method')['Total_Amount'].mean().reset_index()
avg_order_value

  Payment_Method  Total_Amount
0           Cash  15715.246761
1    Credit Card  15755.694077
2     Debit Card  15708.867117
3         PayPal  15985.051394
4            UPI  15718.485191

In [21]:
# Identify the top 5 cities by total sales.
top_5_city = data.groupby('City')['Total_Amount'].size().sort_values(ascending=False).head().reset_index()
top_5_city

      City  Total_Amount
0  Kolkata          7226
1     Pune          7204
2    Delhi          7173
3   Mumbai          7109
4  Chennai          7101

In [34]:
# Find the number of cancelled and returned orders per Category.
cancelled_ordersCategory = data[(data['Order_Status']=="Cancelled") | (data['Order_Status']=='Returned')].groupby('Category').size().reset_index(name='Cancelled & Returned')
cancelled_ordersCategory.head()

          Category  Cancelled & Returned
0      Accessories                  3218
1         Clothing                  3117
2      Electronics                  3111
3  Home Appliances                  3026

In [40]:
# Determine the monthly sales trend.
monthly_sales_trend = data.groupby('Month')['Total_Amount'].sum().reset_index(name='sales')
monthly_sales_trend

    Month        sales
0       1  68115130.58
1       2  59627466.27
2       3  67537961.00
3       4  63527373.68
4       5  68453202.07
5       6  65348485.02
6       7  65305580.76
7       8  69866532.98
8       9  63709882.32
9      10  66157676.69
10     11  63780293.41
11     12  67371550.25

In [56]:
# 5. Customer Behavior Analysis
    # Identify customers who placed more than 4 orders in a single month.

customer_order = data.groupby(['Customer_ID','Month']).size().reset_index(name='order_count')
a=customer_order[customer_order['order_count'] > 4] 
a

       Customer_ID  Month  order_count
319           1068      3            5
1052          1227     12            5
6053          2364     10            5
8058          2823      7            5
9824          3204      7            5
11895         3674     11            5
12312         3768      7            6
20584         5633      2            5
20712         5661      2            5
23318         6247      9            5
23614         6311      9            5
26530         6967     10            5
26798         7026     12            5
28539         7420      3            5
29543         7652      4            5
29635         7671      7            5
29682         7681     12            5
31441         8083     11            5
36037         9106     12            5
37347         9412      9            5
37960         9551      8            5

In [72]:
# identify customer which Product order > 2 time in single month
month_product = data.groupby(['Customer_ID','Product','Month']).size().reset_index(name='product_order')
c = month_product[month_product['product_order']>2]
c

       Customer_ID     Product  Month  product_order
2885          1531      Tablet     11              3
3084          1565       Shoes     11              3
4933          1909      Camera      8              3
6125          2128      Tablet     12              3
8526          2579  Headphones      2              3
9846          2823      Tablet      7              3
10529         2946          TV      3              3
12355         3279       Shoes     12              3
12871         3380      Tablet      5              3
13016         3407          TV     10              3
14466         3674      Camera     11              3
15806         3925       Watch      1              3
18428         4412      Tablet      4              3
24290         5507  Headphones     12              3
26923         5994       Watch      3              3
27044         6017          TV      5              3
28613         6311      Camera      9              3
30110         6587      Camera      4              3
31619         6873      Tablet      3              3
32467         7026       Watch     12              3
34104         7327      Mobile      8              3
34479         7401       Shoes     10              3
35952         7671      Tablet      7              3
42589         8905      Camera      1              3
43306         9031          TV     11              3
44985         9345  Headphones      6              3
45350         9417      Tablet      1              3
45438         9432      Laptop      3              3
45943         9527      Laptop     10              3
47284         9772  Headphones      5              3
48225         9953          TV      4              3

In [73]:
data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year,Discounted_Amount,Price_Level,Revenue_Per_Item,Order_Month
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023,6408.050,Medium,582.55,9
13,14,3433,2024-12-07,Camera,Home Appliances,21,1129.86,Credit Card,Completed,Chennai,23727.06,7,12,2024,21354.354,High,1129.86,12
14,15,6311,2023-09-13,Camera,Clothing,12,153.94,Debit Card,Returned,Mumbai,1847.28,13,9,2023,1847.280,Low,153.94,9
15,16,6051,2023-06-20,TV,Clothing,18,232.77,Debit Card,Completed,Hyderabad,4189.86,20,6,2023,4189.860,Medium,232.77,6
16,17,7420,2024-07-05,Shoes,Accessories,9,1175.99,PayPal,Cancelled,Kolkata,10583.91,5,7,2024,9525.519,High,1175.99,7

In [89]:
# Find customers whose average order value exceeds 25000.
average_order = data.groupby('Customer_ID')['Total_Amount'].mean().reset_index(name='exceeds_1500')
average_order[average_order['exceeds_1500']>25000]

      Customer_ID  exceeds_1500
10           1010  25113.190000
43           1043  31997.762000
49           1049  25316.600000
52           1052  25733.608000
55           1055  27993.286250
...           ...           ...
8890         9926  29367.522500
8900         9936  31671.536667
8920         9956  36847.980000
8934         9970  26731.075000
8961         9997  28929.896667

[705 rows x 2 columns]