In [2]:
import pandas as pd

In [ ]:
# 1. Data Exploration and Cleaning
# Load the dataset into a Pandas DataFrame and display the first 5 rows.

data = pd.read_csv("online_retail_sales_Large.csv")
data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23

In [11]:
# Check the dataset shape, column names, data types, and summary statistics.

print("Dataset shape: \n",data.shape)
print("column names: \n",data.columns.to_list())
print("Data Types: \n",data.dtypes)
print("summary statistics :\n",data.describe())

Dataset shape:
 (50000, 11)
column names:
 ['Order_ID', 'Customer_ID', 'Order_Date', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Payment_Method', 'Order_Status', 'City', 'Total_Amount']
Data Types:
 Order_ID            int64
Customer_ID         int64
Order_Date         object
Product            object
Category           object
Quantity            int64
Unit_Price        float64
Payment_Method     object
Order_Status       object
City               object
Total_Amount      float64
dtype: object
summary statistics :
            Order_ID   Customer_ID      Quantity    Unit_Price  Total_Amount
count  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000
mean   25000.500000   5494.083720     12.493440   1259.940694  15776.022701
std    14433.901067   2601.545347      6.901944    715.936278  13461.642349
min        1.000000   1000.000000      1.000000     20.010000     22.340000
25%    12500.750000   3232.750000      6.000000    639.095000   4619.632500
50%    25000.500000   5497.000000     13.000000   1261.480000  11949.390000
75%    37500.250000   7746.000000     18.000000   1876.660000  23997.630000
max    50000.000000   9999.000000     24.000000   2499.960000  59958.960000

In [14]:
# Identify missing values in each column.
print(data.isnull().sum())

Order_ID          0
Customer_ID       0
Order_Date        0
Product           0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
Order_Status      0
City              0
Total_Amount      0
dtype: int64

In [ ]:
# Handle missing values appropriately:
# Numerical columns: fill with mean or median.
# Categorical columns: fill with mode or drop.

data['Product'] = data['Product'].fillna('Unkown')
data['Unit_Price'] = data['Unit_Price'].fillna(data['Unit_Price'].median())

In [17]:
# Convert Order_Date into datetime format.
data['Order_Date'] = pd.to_datetime(data['Order_Date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        50000 non-null  int64
 1   Customer_ID     50000 non-null  int64
 2   Order_Date      50000 non-null  datetime64[ns]
 3   Product         50000 non-null  object
 4   Category        50000 non-null  object
 5   Quantity        50000 non-null  int64
 6   Unit_Price      50000 non-null  float64
 7   Payment_Method  50000 non-null  object
 8   Order_Status    50000 non-null  object
 9   City            50000 non-null  object
 10  Total_Amount    50000 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 4.2+ MB

In [19]:
# Extract Year, Month, and Day from Order_Date into new columns.
data['Day'] = data['Order_Date'].dt.day
data['Month'] = data['Order_Date'].dt.month
data['Year'] = data['Order_Date'].dt.year
data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,2023
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023

In [22]:
# 2. Data Selection and Filtering
# Retrieve all orders placed in March 2024.
all_order_march_2024 = data[(data['Month']==3) & (data['Year']==2024)]
all_order_march_2024.head(8)

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
32,33,2267,2024-03-04,Laptop,Clothing,6,1892.98,UPI,Completed,Hyderabad,11357.88,4,3,2024
34,35,4556,2024-03-20,TV,Accessories,13,691.15,Cash,Returned,Bangalore,8984.95,20,3,2024
36,37,9838,2024-03-29,TV,Home Appliances,9,1138.31,UPI,Completed,Chennai,10244.79,29,3,2024
64,65,7439,2024-03-20,Shoes,Accessories,10,2078.13,PayPal,Completed,Hyderabad,20781.30,20,3,2024
82,83,3027,2024-03-29,Mobile,Accessories,18,56.06,Cash,Completed,Hyderabad,1009.08,29,3,2024
95,96,8215,2024-03-25,Laptop,Electronics,16,113.54,Debit Card,Completed,Bangalore,1816.64,25,3,2024
125,126,7892,2024-03-11,TV,Accessories,12,1777.17,Cash,Completed,Pune,21326.04,11,3,2024
135,136,6450,2024-03-02,Camera,Home Appliances,15,1222.36,PayPal,Completed,Kolkata,18335.40,2,3,2024

In [25]:
# Find all orders where:
# Total_Amount > 10000
# Category is Electronics.
category_electronic_totalAmount_10000 =  data[(data['Category']=='Electronics') & (data['Total_Amount'] > 10000)]
category_electronic_totalAmount_10000.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
18,19,5555,2023-08-22,Mobile,Electronics,10,2478.51,PayPal,Completed,Bangalore,24785.10,22,8,2023
23,24,8849,2023-08-17,TV,Electronics,19,967.10,PayPal,Cancelled,Bangalore,18374.90,17,8,2023
30,31,2899,2024-07-29,Camera,Electronics,22,2015.96,UPI,Cancelled,Pune,44351.12,29,7,2024
40,41,8513,2024-12-15,Camera,Electronics,19,2336.76,Debit Card,Cancelled,Delhi,44398.44,15,12,2024
56,57,7873,2024-02-20,Headphones,Electronics,23,1348.05,Debit Card,Completed,Delhi,31005.15,20,2,2024

In [28]:
# Select only Completed orders.
completed_order = data[data['Order_Status']=='Completed']
completed_order.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,2023
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,2023
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023

In [39]:
# Retrieve orders placed from Mumbai or Delhi.
orders_placed_Mumbai_Delhi = data[(data['City']=='Pune') | (data['City']=='Mumbai')]
orders_placed_Mumbai_Delhi.head(10)

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Day,Month,Year
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,2023
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,2024
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,2023
10,11,2685,2023-08-25,Watch,Clothing,8,1525.58,UPI,Completed,Pune,12204.64,25,8,2023
14,15,6311,2023-09-13,Camera,Clothing,12,153.94,Debit Card,Returned,Mumbai,1847.28,13,9,2023
20,21,7396,2024-05-07,Shoes,Home Appliances,2,2212.34,PayPal,Cancelled,Mumbai,4424.68,7,5,2024
30,31,2899,2024-07-29,Camera,Electronics,22,2015.96,UPI,Cancelled,Pune,44351.12,29,7,2024
31,32,8734,2023-09-02,Tablet,Home Appliances,13,123.00,UPI,Completed,Pune,1599.00,2,9,2023
35,36,4890,2023-08-21,TV,Clothing,16,1180.10,Credit Card,Completed,Mumbai,18881.60,21,8,2023
37,38,6393,2023-12-15,Tablet,Home Appliances,11,2439.66,Credit Card,Completed,Pune,26836.26,15,12,2023